#!/usr/bin/env python
import rospy
from visualization_msgs.msg import Marker
from sensor_msgs.msg import Image
from lab4_cam.srv import ImageSrv, ImageSrvResponse
import cv2, time, sys
from cv_bridge import CvBridge, CvBridgeError
import numpy as np
from numpy.linalg import *


def AR_tag():
    
    rospy.init_node('AR_tag', anonymous=True)
	rospy.Subscriber("/visualization_marker", Marker)


def cam_pose():
	pub = rospy.Publisher(AR_tag_pose, Marker, queue_size=10)
	rospy.init_node('cam_pose')
	

if __name__ == '__main__':
    try:
        AR_tag()
        cam_pose()
    except rospy.ROSInterruptException:
        pass



